### ISSUE TITLE
Pair Prototyping / Thymeleaf

### ISSUE THREAD

**Issue by SamiDeshatty** [alvinzhengq/AP-CSA#10]
- [ ] Objective is to produce a 3 by 3 grid using Bootstrap Grids, Bootstrap Tables, Bootstrap Cards.  Try to incorporate into Project or consider as Mini Lab depending on your design.  

- [ ] Try changing 3 x 3 to 4 x 4 or other orientation would be showing ability to manage page dynamically.

**Comment by nolanplatt** [comment]
9/12/21 ~ Fixed assignees tab. Should not be assigned to everyone as I am completing it
