### ISSUE TITLE
Teacher Review Week 4

### ISSUE THREAD

**Issue by alvinzhengq** [alvinzhengq/AP-CSA#23]

**Comment by jm1021** [comment]
Discussed tickets, lots of details in tickets.  Perhaps too many people on some tickets.  Lots of research.   1.0

**Comment by ashwinbabu888** [comment]
TOC for README.md needs specific relevant information on the rest of the README content. Needs self grading for individual and team work. 1.5/2.0

**Comment by ashwinbabu888** [comment]
Individual work:
Akshay: 2/2 - good commits, worked on backend and frontend
Alvin: 2/2 - backend and frontend work, good job
Nolan: 2/2 - lots of commits for all aspects of the website
Sami: 0.5/2 - all of the commits are generally styling minimal things or changing text. no significant contributions to backend and mechanics of the website
Prisha: 0/2 - no commits besides README.md, changing barely any text, and adding a blank line

**Comment by ashwinbabu888** [comment]
Team work (Unit 4 + journals):
Akshay: 5/5
Alvin: 5/5
Nolan: 5/5
Sami: 5/5
Prisha: 5/5
