### ISSUE TITLE
Select Images and Provide Grayscale or Original

### ISSUE THREAD

**Issue by PrishaMaiti** [alvinzhengq/AP-CSA#28]

**Comment by Akshay-Rohatgi** [comment]
Use the [grayscale ](https://github.com/nighthawkcoders/nighthawk_csa/blob/e0bf367a986a1a488a4617ccd9dcccdc80fb7afa/src/main/java/com/nighthawk/csa/model/starters/ImageInfo.java#L63) method in order to return grayscale image encoded as a base64 string
