### ISSUE TITLE
Decide on Final Name and Design for MV Fetch

### ISSUE THREAD

**Issue by alvinzhengq** [alvinzhengq/AP-CSA#5]

**Comment by nolanplatt** [comment]
Current name/logo is placeholder as team awaits final name, design and logo for production.

**Comment by Akshay-Rohatgi** [comment]
Name Decided as **Distraction**

Final Design:
https://www.figma.com/file/kJd7CpPpR3EzCu3Fo0LBS3/Distraction?node-id=101%3A47
