### ISSUE TITLE
Pair Design/ HTML

### ISSUE THREAD

**Issue by SamiDeshatty** [alvinzhengq/AP-CSA#9]
Transfer design to layout.  Much of this could simply be converting Ideas to HTML.  Objective is to get your own STYLE, COLORS, FONTS; NAVIGATION into the site.  Establish your VIBE or Groove.  Try a couple of prototype experiments and get feedback from similar pair in Crossover.

- [x] Choose colors and add to CSS
- [x] Finish login page
- [x] Finish home page
- [x] Finish Movie list page

**Comment by Akshay-Rohatgi** [comment]
Here is the new Figma Design We'll start converting pages to HTML.
https://www.figma.com/file/kJd7CpPpR3EzCu3Fo0LBS3/Distraction?node-id=6%3A348
